/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controle.de.qualidade;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Bruno
 */
public class UIFMenu extends javax.swing.JFrame {

	private Funcionario f;
	private JPanel novo;
	private TableModel visualizar_av_venda_model;
	private TableModel visualizar_av_atendimentos_model;
	private TableModel visualizar_av_serv_oficina_model;
	private Vector avaliacoes_vendas;
	private Vector avaliacoes_atendimentos;
	private Vector avaliacoes_oficina;
	private Cliente c;

	/**
	 * Creates new form FMenu
	 *
	 * @param f
	 */
	public UIFMenu(Funcionario f) {
		initComponents();
		BemVindoPanel.setVisible(true);
		ClientePanel.setVisible(false);
		DadosProdutosPanel.setVisible(false);
		DadosSetoresPanel.setVisible(false);
		FuncionarioPanel.setVisible(false);
		GeralPanel.setVisible(false);
		LimparPanel.setVisible(false);
		ProdutoPanel.setVisible(false);
		SairPanel.setVisible(false);
		SetorPanel.setVisible(false);
		TableClientesPanel.setVisible(false);
		TableFuncionariosPanel.setVisible(false);
		TableGeralPanel.setVisible(false);
		TableSetorPanel.setVisible(false);

		this.f = f;
		jLabel16.setText(f.getNome());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel53 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        GeralPanel = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        warningLabelGeral = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable18 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable19 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jPanel21 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel47 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter dataIni = new javax.swing.text.MaskFormatter("##/##/####");
            dataIni.setPlaceholderCharacter('_');
            jTextField1 = new javax.swing.JFormattedTextField(dataIni);
        }catch(Exception e){
        }
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter dataFim = new javax.swing.text.MaskFormatter("##/##/####");
            dataFim.setPlaceholderCharacter('_');
            jTextField2 = new javax.swing.JFormattedTextField(dataFim);
        }catch(Exception e){
        }
        jButton22 = new javax.swing.JButton();
        SetorPanel = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter dataIni = new javax.swing.text.MaskFormatter("##/##/####");
            dataIni.setPlaceholderCharacter('_');
            jTextField3 = new javax.swing.JFormattedTextField(dataIni);
        }catch(Exception e){
        }
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter dataFim = new javax.swing.text.MaskFormatter("##/##/####");
            dataFim.setPlaceholderCharacter('_');
            jTextField4 = new javax.swing.JFormattedTextField(dataFim);
        }catch(Exception e){
        }
        jPanel26 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel31 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jPanel32 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        ClientePanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter CPF = new javax.swing.text.MaskFormatter("###.###.###-##");
            CPF.setPlaceholderCharacter('_');
            jTextField6 = new javax.swing.JFormattedTextField(CPF);
        }catch(Exception e){
        }
        jLabel30 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable15 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel65 = new javax.swing.JPanel();
        warningLabel = new javax.swing.JLabel();
        FuncionarioPanel = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter CPF = new javax.swing.text.MaskFormatter("###.###.###-##");
            CPF.setPlaceholderCharacter('_');
            jTextField11 = new javax.swing.JFormattedTextField(CPF);
        }catch(Exception e){
        }
        jLabel45 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jPanel69 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jPanel70 = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable16 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable17 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jPanel71 = new javax.swing.JPanel();
        warningLabelFuncionario = new javax.swing.JLabel();
        ProdutoPanel = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        LimparPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter dataIni = new javax.swing.text.MaskFormatter("##/##/####");
            dataIni.setPlaceholderCharacter('_');
            jTextField5 = new javax.swing.JFormattedTextField(dataIni);
        }catch(Exception e){
        }
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter dataFim = new javax.swing.text.MaskFormatter("##/##/####");
            dataFim.setPlaceholderCharacter('_');
            jTextField9 = new javax.swing.JFormattedTextField(dataFim);
        }catch(Exception e){
        }
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        DadosSetoresPanel = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        DadosProdutosPanel = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        SairPanel = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        BemVindoPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        TableClientesPanel = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jPanel58 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        TableFuncionariosPanel = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jPanel60 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        TableGeralPanel = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jPanel62 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        TableSetorPanel = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex){
                return false;
            }
        };
        jPanel64 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jDialog1.setTitle("Limpar Histórico");
        jDialog1.setMinimumSize(new java.awt.Dimension(400, 230));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel53.setLayout(new java.awt.GridLayout(2, 0));

        jPanel56.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Período:");
        jPanel56.add(jLabel25);

        jPanel53.add(jPanel56);

        jPanel57.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("De:");
        jPanel57.add(jLabel26);

        jLabel27.setText("01/01/2014");
        jPanel57.add(jLabel27);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Até:");
        jPanel57.add(jLabel28);

        jLabel29.setText("31/12/2014");
        jPanel57.add(jLabel29);

        jPanel53.add(jPanel57);

        jDialog1.getContentPane().add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 80));

        jPanel54.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Você tem certeza que deseja limpar o histórico?");
        jPanel54.add(jLabel24);

        jDialog1.getContentPane().add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 40));

        jButton11.setText("Voltar");
        jPanel55.add(jButton11);

        jButton10.setText("Limpar");
        jPanel55.add(jButton10);

        jDialog1.getContentPane().add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Funcionário");
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Histórico - Geral");
        jPanel15.add(jLabel18);

        warningLabelGeral.setForeground(new java.awt.Color(204, 0, 0));
        warningLabelGeral.setText("warningLabelGeral");
        jPanel13.add(warningLabelGeral);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTable18.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable18FocusGained(evt);
            }
        });
        jScrollPane18.setViewportView(jTable18);

        jTable19.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable19.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable19FocusGained(evt);
            }
        });
        jScrollPane19.setViewportView(jTable19);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 9));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Visualizar Avaliação");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Período:");
        jPanel47.add(jLabel2);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Oficina");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        jLabel21.setText("Venda");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel53.setText("Atendimento");
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jLabel1.setText("De: ");
        jPanel14.add(jLabel1);

        jTextField1.setColumns(8);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel14.add(jTextField1);

        jLabel3.setText("Até: ");
        jPanel14.add(jLabel3);

        jTextField2.setColumns(8);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel14.add(jTextField2);

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton22.setText("Buscar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton22);

        javax.swing.GroupLayout GeralPanelLayout = new javax.swing.GroupLayout(GeralPanel);
        GeralPanel.setLayout(GeralPanelLayout);
        GeralPanelLayout.setHorizontalGroup(
            GeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeralPanelLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GeralPanelLayout.setVerticalGroup(
            GeralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeralPanelLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(GeralPanel);

        SetorPanel.setLayout(new java.awt.GridLayout(4, 0));

        jPanel46.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Histórico - Setor");
        jPanel46.add(jLabel19);

        SetorPanel.add(jPanel46);

        jPanel18.setLayout(new java.awt.GridLayout(3, 0, 0, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Período:");
        jPanel48.add(jLabel4);

        jPanel18.add(jPanel48);

        jLabel5.setText("De: ");
        jPanel19.add(jLabel5);

        jTextField3.setColumns(8);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField3);

        jLabel6.setText("Até: ");
        jPanel19.add(jLabel6);

        jTextField4.setColumns(8);
        jPanel19.add(jTextField4);

        jPanel18.add(jPanel19);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Venda");
        jPanel26.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Atendimento");
        jPanel26.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Oficina");
        jPanel26.add(jRadioButton3);

        jPanel18.add(jPanel26);

        SetorPanel.add(jPanel18);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel31.add(jScrollPane2);

        SetorPanel.add(jPanel31);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton6.setText("Confirmar");
        jPanel32.add(jButton6);

        SetorPanel.add(jPanel32);

        getContentPane().add(SetorPanel);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Histórico - Cliente");
        jPanel5.add(jLabel20);

        jLabel9.setText("CPF do Cliente:");
        jPanel17.add(jLabel9);

        jTextField6.setColumns(11);
        jTextField6.setToolTipText("");
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel17.add(jTextField6);

        jLabel30.setText("11 Dígitos");
        jPanel17.add(jLabel30);

        jPanel20.add(jPanel6);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton2);

        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable13FocusGained(evt);
            }
        });
        jScrollPane6.setViewportView(jTable13);

        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable14FocusGained(evt);
            }
        });
        jScrollPane7.setViewportView(jTable14);

        jTable15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable15FocusGained(evt);
            }
        });
        jScrollPane8.setViewportView(jTable15);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Avaliações ");

        jLabel40.setText("Vendas");

        jLabel35.setText("Nome do Cliente:");

        jLabel38.setText("12345678912");

        jLabel37.setText("CPF:");

        jLabel36.setText("Zé");

        jLabel41.setText("Atendimento");

        jLabel42.setText("Oficina");

        jButton4.setText("Visualizar Avaliação");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(213, 213, 213)
                .addComponent(jLabel42)
                .addGap(101, 101, 101))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(357, 357, 357))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel36))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(64, 64, 64))
        );

        warningLabel.setForeground(new java.awt.Color(204, 0, 0));
        jPanel65.add(warningLabel);

        javax.swing.GroupLayout ClientePanelLayout = new javax.swing.GroupLayout(ClientePanel);
        ClientePanel.setLayout(ClientePanelLayout);
        ClientePanelLayout.setHorizontalGroup(
            ClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel65, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ClientePanelLayout.setVerticalGroup(
            ClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientePanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel65, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(ClientePanel);

        jPanel66.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Histórico - Funcionário");
        jPanel66.add(jLabel43);

        jLabel44.setText("CPF do Funcionário:");
        jPanel67.add(jLabel44);

        jTextField11.setColumns(11);
        jTextField11.setToolTipText("");
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        jPanel67.add(jTextField11);

        jLabel45.setText("11 Dígitos");
        jPanel67.add(jLabel45);

        jPanel68.add(jPanel69);

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton20.setText("Confirmar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel68.add(jButton20);

        jTable16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable16FocusGained(evt);
            }
        });
        jScrollPane16.setViewportView(jTable16);

        jTable17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable17FocusGained(evt);
            }
        });
        jScrollPane17.setViewportView(jTable17);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setText("Avaliações ");

        jLabel47.setText("Vendas");

        jLabel48.setText("Nome do Funcionário:");

        jLabel49.setText("12345678912");

        jLabel50.setText("CPF:");

        jLabel51.setText("Zé");

        jLabel52.setText("Atendimento");

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton21.setText("Visualizar Avaliação");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52)
                .addGap(188, 188, 188))
            .addGroup(jPanel70Layout.createSequentialGroup()
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel70Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel70Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel49))
                            .addGroup(jPanel70Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel51)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel70Layout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(370, 370, 370))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                        .addComponent(jButton21)
                        .addGap(332, 332, 332))))
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel70Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jLabel49))
                .addGap(15, 15, 15)
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton21)
                .addContainerGap())
        );

        warningLabelFuncionario.setForeground(new java.awt.Color(204, 0, 0));
        jPanel71.add(warningLabelFuncionario);

        javax.swing.GroupLayout FuncionarioPanelLayout = new javax.swing.GroupLayout(FuncionarioPanel);
        FuncionarioPanel.setLayout(FuncionarioPanelLayout);
        FuncionarioPanelLayout.setHorizontalGroup(
            FuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel71, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel67, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
            .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionarioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FuncionarioPanelLayout.setVerticalGroup(
            FuncionarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionarioPanelLayout.createSequentialGroup()
                .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel68, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(FuncionarioPanel);

        ProdutoPanel.setLayout(new java.awt.GridLayout(5, 0));
        ProdutoPanel.add(jPanel24);

        jLabel11.setText("Cod. Produto");
        jPanel25.add(jLabel11);

        jTextField8.setColumns(20);
        jPanel25.add(jTextField8);

        ProdutoPanel.add(jPanel25);
        ProdutoPanel.add(jPanel10);
        ProdutoPanel.add(jPanel11);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton5.setText("Confirmar");
        jPanel12.add(jButton5);

        ProdutoPanel.add(jPanel12);

        getContentPane().add(ProdutoPanel);

        LimparPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(5, 0));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Limpar Histórico");
        jPanel35.add(jLabel22);

        jPanel1.add(jPanel35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Período:");
        jPanel33.add(jLabel7);

        jPanel1.add(jPanel33);

        jLabel8.setText("De: ");
        jPanel34.add(jLabel8);

        jTextField5.setColumns(8);
        jPanel34.add(jTextField5);

        jLabel12.setText("Até: ");
        jPanel34.add(jLabel12);

        jTextField9.setColumns(8);
        jPanel34.add(jTextField9);

        jPanel1.add(jPanel34);
        jPanel1.add(jPanel36);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton7.setText("Confirmar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel37.add(jButton7);

        jPanel1.add(jPanel37);

        LimparPanel.add(jPanel1);

        getContentPane().add(LimparPanel);

        DadosSetoresPanel.setLayout(new java.awt.GridLayout(4, 0));

        jPanel44.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Sumarização");
        jPanel44.add(jLabel23);

        DadosSetoresPanel.add(jPanel44);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("Geral");
        jPanel49.add(jRadioButton7);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Venda");
        jPanel49.add(jRadioButton4);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Atendimento");
        jPanel49.add(jRadioButton5);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Oficina");
        jPanel49.add(jRadioButton6);

        DadosSetoresPanel.add(jPanel49);
        DadosSetoresPanel.add(jPanel50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Confirmar");
        jPanel51.add(jButton1);

        DadosSetoresPanel.add(jPanel51);

        getContentPane().add(DadosSetoresPanel);

        DadosProdutosPanel.setLayout(new java.awt.GridLayout(5, 0));
        DadosProdutosPanel.add(jPanel39);

        jLabel13.setText("Cod. Produto");
        jPanel40.add(jLabel13);

        jTextField10.setColumns(20);
        jPanel40.add(jTextField10);

        DadosProdutosPanel.add(jPanel40);
        DadosProdutosPanel.add(jPanel41);
        DadosProdutosPanel.add(jPanel42);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton8.setText("Confirmar");
        jPanel43.add(jButton8);

        DadosProdutosPanel.add(jPanel43);

        getContentPane().add(DadosProdutosPanel);

        SairPanel.setLayout(new java.awt.GridLayout(5, 0));
        SairPanel.add(jPanel28);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("Deseja voltar ao menu inicial?");
        jPanel29.add(jLabel14);

        SairPanel.add(jPanel29);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("Confirmar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton9);

        SairPanel.add(jPanel30);

        getContentPane().add(SairPanel);

        BemVindoPanel.setLayout(new java.awt.GridLayout(5, 0));
        BemVindoPanel.add(jPanel2);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Bem Vindo");
        jPanel3.add(jLabel15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel3.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("!");
        jPanel3.add(jLabel17);

        BemVindoPanel.add(jPanel3);
        BemVindoPanel.add(jPanel27);
        BemVindoPanel.add(jPanel38);
        BemVindoPanel.add(jPanel45);

        getContentPane().add(BemVindoPanel);

        TableClientesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Cliente");
        jPanel52.add(jLabel31);

        TableClientesPanel.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        TableClientesPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 230));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        TableClientesPanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 220, 230));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable5);

        TableClientesPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 200, 230));

        jButton15.setText("Fechar");
        jPanel58.add(jButton15);

        jButton12.setText("Confirmar");
        jPanel58.add(jButton12);

        TableClientesPanel.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 640, 60));

        getContentPane().add(TableClientesPanel);

        TableFuncionariosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Funcionario");
        jPanel59.add(jLabel32);

        TableFuncionariosPanel.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(jTable6);

        TableFuncionariosPanel.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 230));

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTable7);

        TableFuncionariosPanel.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 220, 230));

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane11.setViewportView(jTable8);

        TableFuncionariosPanel.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 200, 230));

        jButton14.setText("Fechar");
        jPanel60.add(jButton14);

        jButton13.setText("Confirmar");
        jPanel60.add(jButton13);

        TableFuncionariosPanel.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 640, 60));

        getContentPane().add(TableFuncionariosPanel);

        TableGeralPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Geral");
        jPanel61.add(jLabel33);

        TableGeralPanel.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane12.setViewportView(jTable9);

        TableGeralPanel.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 230));

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane13.setViewportView(jTable10);

        TableGeralPanel.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 220, 230));

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane14.setViewportView(jTable11);

        TableGeralPanel.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 200, 230));

        jButton16.setText("Fechar");
        jPanel62.add(jButton16);

        jButton17.setText("Confirmar");
        jPanel62.add(jButton17);

        TableGeralPanel.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 640, 60));

        getContentPane().add(TableGeralPanel);

        TableSetorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("Setor");
        jPanel63.add(jLabel34);

        TableSetorPanel.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane15.setViewportView(jTable12);

        TableSetorPanel.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 230));

        jButton18.setText("Fechar");
        jPanel64.add(jButton18);

        jButton19.setText("Confirmar");
        jPanel64.add(jButton19);

        TableSetorPanel.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 400, 30));

        getContentPane().add(TableSetorPanel);

        jMenu6.setText("Histórico");

        jMenu1.setText("Visualizar");

        jMenuItem1.setText("Geral");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Setor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Cliente");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Funcionario");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenu6.add(jMenu1);

        jMenuItem8.setText("Limpar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Sumarização");

        jMenuItem6.setText("Setor");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem6);

        jMenuBar1.add(jMenu7);

        jMenu5.setText("Sair");

        jMenuItem9.setText("Logout");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(822, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	private void setVisibleAllFalse() {
		BemVindoPanel.setVisible(false);
		ClientePanel.setVisible(false);
		DadosProdutosPanel.setVisible(false);
		DadosSetoresPanel.setVisible(false);
		FuncionarioPanel.setVisible(false);
		GeralPanel.setVisible(false);
		LimparPanel.setVisible(false);
		ProdutoPanel.setVisible(false);
		SairPanel.setVisible(false);
		SetorPanel.setVisible(false);
		TableClientesPanel.setVisible(false);
		TableFuncionariosPanel.setVisible(false);
		TableGeralPanel.setVisible(false);
		TableSetorPanel.setVisible(false);
	}
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		setVisibleAllFalse();
		GeralPanel.setVisible(true);
		jPanel7.setVisible(false);
		jPanel16.setVisible(false);
		jPanel21.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		setVisibleAllFalse();
		SetorPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
		setVisibleAllFalse();
		ClientePanel.setVisible(true);
		jPanel4.setVisible(false);
		jTextField6.requestFocus();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
		setVisibleAllFalse();
		FuncionarioPanel.setVisible(true);
		jPanel70.setVisible(false);
		jTextField11.requestFocus();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
		setVisibleAllFalse();
		DadosSetoresPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
		setVisibleAllFalse();
		LimparPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
		setVisibleAllFalse();
		SairPanel.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
		new UILogin().setVisible(true);
		this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:
		jDialog1.setLocationRelativeTo(null);
		jDialog1.setSize(400, 230);
		jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		try {
			this.buscarClientePanel();
		} catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
			jPanel4.setVisible(false);
			warningLabel.setText("Erro: Falha na conexão com o BD");
			Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
		String cpf = jTextField6.getText().replaceAll("[^0-9]", "");
		jTextField6.setText(cpf);
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			try {
				this.buscarClientePanel();
			} catch (SQLException ex) {
				jPanel4.setVisible(false);
				warningLabel.setText("Erro: Falha na conexão com o BD");
				Logger.getLogger(UILogin.class.getName()).log(Level.SEVERE, null, ex);
			} catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
				Logger.getLogger(UILogin.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
		String cpf = jTextField11.getText().replaceAll("[^0-9]", "");
		jTextField11.setText(cpf);
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			try {
				this.buscarFuncionarioPanel();
			} catch (SQLException ex) {
				jPanel70.setVisible(false);
				warningLabelFuncionario.setText("Erro: Falha na conexão com o BD");
				Logger.getLogger(UILogin.class.getName()).log(Level.SEVERE, null, ex);
			} catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
				Logger.getLogger(UILogin.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
		try {
			this.buscarFuncionarioPanel();
		} catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
			jPanel70.setVisible(false);
			warningLabelFuncionario.setText("Erro: Falha na conexão com o BD");
			Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTable13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable13FocusGained
		jTable14.clearSelection();
		jTable15.clearSelection();
    }//GEN-LAST:event_jTable13FocusGained

    private void jTable14FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable14FocusGained
		jTable13.clearSelection();
		jTable15.clearSelection();
    }//GEN-LAST:event_jTable14FocusGained

    private void jTable15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable15FocusGained
		jTable13.clearSelection();
		jTable14.clearSelection();
    }//GEN-LAST:event_jTable15FocusGained

    private void jTable16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable16FocusGained
		jTable17.clearSelection();
    }//GEN-LAST:event_jTable16FocusGained

    private void jTable17FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable17FocusGained
		jTable16.clearSelection();
    }//GEN-LAST:event_jTable17FocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
		int row = -1;
		int opc = -1;

		if (row == -1) {
			row = jTable13.getSelectedRow();
			opc = 1;
		}
		if (row == -1) {
			row = jTable14.getSelectedRow();
			opc = 2;
		}
		if (row == -1) {
			row = jTable15.getSelectedRow();
			opc = 3;
		}

		if (opc == 1) {
			AvVenda av = (AvVenda) avaliacoes_vendas.get(row);
			new UIVisAvVenda(c, av).setVisible(true);
		} else if (opc == 2) {
			AvAtendimento av = (AvAtendimento) avaliacoes_atendimentos.get(row);
			new UIVisAvAtendimento(c, av).setVisible(true);
		} else if (opc == 3) {
			AvOficina av = (AvOficina) avaliacoes_oficina.get(row);
			new UIVisAvOficina(c, av).setVisible(true);
		}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
		int opc = -1;
		int row = -1;

		if (row == -1) {
			row = jTable16.getSelectedRow();
			opc = 1;
		}
		if (row == -1) {
			row = jTable17.getSelectedRow();
			opc = 2;
		}

		System.out.println("" + row);
		if (opc == 1) {
			try {
				AvVenda av = (AvVenda) avaliacoes_vendas.get(row);
				String cpf = av.getCpf_cliente();
				c = new Cliente();
				c.buscarCliente(cpf);
				new UIVisAvVenda(c, av).setVisible(true);
			} catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
				Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else if (opc == 2) {
			try {
				AvAtendimento av = (AvAtendimento) avaliacoes_atendimentos.get(row);
				String cpf = av.getCpf_cliente();
				c = new Cliente();
				c.buscarCliente(cpf);
				c.buscarCliente(av.getCpf_cliente());
				new UIVisAvAtendimento(c, av).setVisible(true);
			} catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
				Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
		jTable18.clearSelection();
		jTable19.clearSelection();
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable18FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable18FocusGained
		jTable1.clearSelection();
		jTable19.clearSelection();
    }//GEN-LAST:event_jTable18FocusGained

    private void jTable19FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable19FocusGained
		jTable1.clearSelection();
		jTable18.clearSelection();
    }//GEN-LAST:event_jTable19FocusGained

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
		try {
			buscarGeral();
		} catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
			Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
		String data = jTextField1.getText().replaceAll("[^0-9]", "");
		jTextField1.setText(data);
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
		String data = jTextField2.getText().replaceAll("[^0-9]", "");
		jTextField2.setText(data);
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		int row = -1;
		int opc = -1;

		if (row == -1) {
			row = jTable1.getSelectedRow();
			opc = 1;
		}
		if (row == -1) {
			row = jTable18.getSelectedRow();
			opc = 2;
		}
		if (row == -1) {
			row = jTable19.getSelectedRow();
			opc = 3;
		}

		if (opc == 1) {
			try {
				AvVenda av = (AvVenda) avaliacoes_vendas.get(row);
				c.buscarCliente(av.getCpf_cliente());
				new UIVisAvVenda(c, av).setVisible(true);
			} catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
				Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else if (opc == 2) {
			try {
				AvAtendimento av = (AvAtendimento) avaliacoes_atendimentos.get(row);
				c.buscarCliente(av.getCpf_cliente());
				new UIVisAvAtendimento(c, av).setVisible(true);
			} catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
				Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		} else if (opc == 3) {
			try {
				AvOficina av = (AvOficina) avaliacoes_oficina.get(row);
				c.buscarCliente(av.getCpf_cliente());
				new UIVisAvOficina(c, av).setVisible(true);
			} catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
				Logger.getLogger(UIFMenu.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_jButton3ActionPerformed

	private void buscarGeral() throws ClassNotFoundException, SQLException, InstantiationException, IllegalAccessException {
		String data_ini = jTextField1.getText();
		String data_fim = jTextField2.getText();

		//IMPLEMENTA AQUI DAVY!! faz as verificações de data e tal. tem q ver se mês > 12 ou se ta certo.
		//tem também que ver se só tem número e se ta do tamanho certo.
		//data_ini e data_fim tb fazem a busca no formato AAAA/MM/DD, mas o usuário digita DD/MM/AAAA, então
		//tem que mudar isso. (já fiz o baratin que não pode clicar no meio do field)
		avaliacoes_vendas = f.obterAvVendasGeral(data_ini, data_fim);
		avaliacoes_atendimentos = f.obterAvAtendimentosGeral(data_ini, data_fim);
		avaliacoes_oficina = f.obterAvOficinaGeral(data_ini, data_fim);

		this.cria_model_visualizar_av_venda();
		this.cria_model_visualizar_av_atendimento();
		this.cria_model_visalizar_av_serv_oficina();

		jPanel7.setVisible(true);
		jPanel16.setVisible(true);
		jPanel21.setVisible(true);
	}

	private void buscarFuncionarioPanel() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
		Funcionario ftemp = new Funcionario();
		String cpf = jTextField11.getText().replaceAll("[^0-9]", "");
		warningLabelFuncionario.setText("");
		jPanel70.setVisible(false);
		if (cpf.length() != 11) {
			jPanel70.setVisible(false);
			warningLabelFuncionario.setText("CPF Inválido!");
			return;
		}
		jLabel49.setText(jTextField11.getText());
		if (ftemp.buscarFuncionario(cpf)) {
			jPanel70.setVisible(true);
			jLabel51.setText(ftemp.getNome());
			this.avaliacoes_vendas = ftemp.obterAvVendasFunc();
			this.avaliacoes_atendimentos = ftemp.obterAvAtendimentosFunc();

			cria_model_visualizar_av_venda_func();
			cria_model_visualizar_av_atendimento_func();

			jTable16.setModel(visualizar_av_venda_model);
			jTable17.setModel(visualizar_av_atendimentos_model);
			jTable16.setSelectionMode(SINGLE_SELECTION);
			jTable17.setSelectionMode(SINGLE_SELECTION);
			//jTable18.setModel(visualizar_av_serv_oficina_model);
		} else {
			warningLabelFuncionario.setText("Funcionário não encontrado!");
		}
		jTextField11.setText("");
	}

	private void buscarClientePanel() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException {
		c = new Cliente();
		String cpf = jTextField6.getText().replaceAll("[^0-9]", "");
		warningLabel.setText("");
		if (cpf.length() != 11) {
			jPanel4.setVisible(false);
			warningLabel.setText("CPF Inválido!");
			return;
		}
		jLabel38.setText(jTextField6.getText());
		if (c.buscarCliente(cpf)) {
			jPanel4.setVisible(true);
			jLabel36.setText(c.getNome());
			this.avaliacoes_vendas = c.obterAvVendas();
			this.avaliacoes_atendimentos = c.obterAvAtendimentos();
			this.avaliacoes_oficina = c.obterAvOficina();

			cria_model_visualizar_av_venda();
			cria_model_visualizar_av_atendimento();
			cria_model_visalizar_av_serv_oficina();

			jTable13.setModel(visualizar_av_venda_model);
			jTable14.setModel(visualizar_av_atendimentos_model);
			jTable15.setModel(visualizar_av_serv_oficina_model);

			jTable13.setSelectionMode(SINGLE_SELECTION);
			jTable14.setSelectionMode(SINGLE_SELECTION);
			jTable15.setSelectionMode(SINGLE_SELECTION);
		} else {
			warningLabel.setText("Cliente não encontrado!");
		}
		jTextField6.setText("");
	}

	private void cria_model_visualizar_av_venda() {
		//magica
		String rows[] = avaliacoes_vendas.toString().replace("[", "").replace("]", "").split(",");
		Vector<Vector<String>> dataVector = new Vector<Vector<String>>();
		for (String row : rows) {
			row = row.trim();  //UPDATE
			Vector<String> data = new Vector<String>();
			data.addAll(Arrays.asList(row.split("@")));
			dataVector.add(data);
		}
		Vector<String> header = new Vector<String>(2);
		header.add("Tipo da Compra");
		header.add("Data Avaliação");
		header.add("Vendedor");
		header.add("Nota");
		visualizar_av_venda_model = new DefaultTableModel(dataVector, header);
	}

	private void cria_model_visualizar_av_venda_func() {
		//magica
		String rows[] = avaliacoes_vendas.toString().replace("[", "").replace("]", "").split(",");
		Vector<Vector<String>> dataVector = new Vector<Vector<String>>();
		for (String row : rows) {
			row = row.trim();  //UPDATE
			Vector<String> data = new Vector<String>();
			data.addAll(Arrays.asList(row.split("@")));
			dataVector.add(data);
		}
		Vector<String> header = new Vector<String>(2);
		header.add("Tipo da Compra");
		header.add("Data Avaliação");
		header.add("Cliente");
		header.add("Nota");
		visualizar_av_venda_model = new DefaultTableModel(dataVector, header);
	}

	private void cria_model_visualizar_av_atendimento() {
		//magica
		String rows[] = avaliacoes_atendimentos.toString().replace("[", "").replace("]", "").split(",");
		Vector<Vector<String>> dataVector = new Vector<Vector<String>>();
		for (String row : rows) {
			row = row.trim();  //UPDATE
			Vector<String> data = new Vector<String>();
			data.addAll(Arrays.asList(row.split("@")));
			dataVector.add(data);
		}
		Vector<String> header = new Vector<String>(2);
		header.add("Atendente");
		header.add("Data Avaliacao");
		header.add("Nota");
		visualizar_av_atendimentos_model = new DefaultTableModel(dataVector, header);
	}

	private void cria_model_visualizar_av_atendimento_func() {
		//magica
		String rows[] = avaliacoes_atendimentos.toString().replace("[", "").replace("]", "").split(",");
		Vector<Vector<String>> dataVector = new Vector<Vector<String>>();
		for (String row : rows) {
			row = row.trim();  //UPDATE
			Vector<String> data = new Vector<String>();
			data.addAll(Arrays.asList(row.split("@")));
			dataVector.add(data);
		}
		Vector<String> header = new Vector<String>(2);
		header.add("Cliente");
		header.add("Data Avaliacao");
		header.add("Nota");
		visualizar_av_atendimentos_model = new DefaultTableModel(dataVector, header);
	}

	private void cria_model_visalizar_av_serv_oficina() {
		//magica
		String rows[] = avaliacoes_oficina.toString().replace("[", "").replace("]", "").split(",");
		Vector<Vector<String>> dataVector = new Vector<Vector<String>>();
		for (String row : rows) {
			row = row.trim();  //UPDATE
			Vector<String> data = new Vector<String>();
			data.addAll(Arrays.asList(row.split("@")));
			dataVector.add(data);
		}
		Vector<String> header = new Vector<String>(2);
		header.add("Placa");
		header.add("Data Avaliacao");
		header.add("Nota");
		visualizar_av_serv_oficina_model = new DefaultTableModel(dataVector, header);
	}
	/**
	 * @param args the command line arguments
	 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BemVindoPanel;
    private javax.swing.JPanel ClientePanel;
    private javax.swing.JPanel DadosProdutosPanel;
    private javax.swing.JPanel DadosSetoresPanel;
    private javax.swing.JPanel FuncionarioPanel;
    private javax.swing.JPanel GeralPanel;
    private javax.swing.JPanel LimparPanel;
    private javax.swing.JPanel ProdutoPanel;
    private javax.swing.JPanel SairPanel;
    private javax.swing.JPanel SetorPanel;
    private javax.swing.JPanel TableClientesPanel;
    private javax.swing.JPanel TableFuncionariosPanel;
    private javax.swing.JPanel TableGeralPanel;
    private javax.swing.JPanel TableSetorPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable16;
    private javax.swing.JTable jTable17;
    private javax.swing.JTable jTable18;
    private javax.swing.JTable jTable19;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JLabel warningLabelFuncionario;
    private javax.swing.JLabel warningLabelGeral;
    // End of variables declaration//GEN-END:variables
}
